- name: copy packages of ntp to node
  copy: src=../packages/ntp/ dest=/tmp/packages/ntp/

- name: copy packages of ceph to node
  copy: src=../packages/ceph/ dest=/tmp/packages/ceph/

- name: install ntp
  command: dpkg -i -R /tmp/packages/ntp/

- name: install ceph
  command: dpkg -i -R /tmp/packages/ceph/
