- name: set up ntp server
  template: src=ntp.conf.j2 dest=/etc/ntp.conf

- name: restart service of ntp
  service: name=ntp state=restarted enabled=yes

- name: save IP of ntp server
  local_action: copy content={{ groups['ntp-server'][0] }} dest=./tmp/ntp_server_ip
