- include_vars: group_vars/deploy

# Check the network in deployment
- name: Set regular expression pattern for checking
  set_fact: pattern="^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\/([0-9]|[1-2][0-9]|3[0-2])"

- name: Check the ip segment format of public network
  fail: msg="The format of public network is wrong!"
  when: public_network is not none and not public_network | match(pattern)

- name: Check the ip segment format of cluster network
  fail: msg="The format of cluster network is wrong!"
  when: cluster_network is not none and not cluster_network | match(pattern)

# Check the user name
- name: Check the user name which can't be 'ceph'
  fail: msg="The name of user can't be 'ceph'. That is the default user for ceph proccess"
  when: user == "ceph"

# OSD config
- name: Check the max size of pool must bigger than or equal min size
  fail: msg="The max size must bigger than or equal to min size."
  when: osd_pool_default_size < osd_pool_default_min_size

- name: Check the nearfull ratio should be less than full ratio
  fail: msg="The osd nearfull ratio should less than osd full ratio."
  when: mon_osd_nearfull_ratio > mon_osd_full_ratio

- name: Check the backfill full ratio should be less than full ratio
  fail: msg="The osd backfill full ratio should be less than osd full ratio."
  when: osd_backfill_full_ratio > mon_osd_full_ratio
