- name: check ntp server ip exist or not
  local_action: stat path=./tmp/ntp_server_ip
  register: ip_exists

- name: set up ntp client
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  when: ip_exists | success

- name: restart service of ntp
  service: name=ntp state=restarted enabled=yes
