- hosts: deploy
  become: yes
  roles:
    - deploy-node

- hosts: ceph-node
  become: yes
  tasks:
    - include: roles/ceph-node/tasks/initialize.yml
    - include: roles/ceph-node/tasks/setup_ntp.yml

- hosts: rados-node
  become: yes
  tasks:
    - include: roles/rados-node/tasks/install.yml

- hosts: client
  become: yes
  tasks:
    - include: roles/client-node/tasks/install.yml

- hosts: radosgw
  become: yes
  tasks:
    - include: roles/radosgw-node/tasks/install.yml
