---
  - include: check_hosts_config.yml

  ## initialize (setup config and install package)
  # need sudo privilege
  - include: sync_hosts_info.yml
  - include: setup_ntp_server.yml
  - include: initial_nodes.yml

  # Start deploying Ceph cluster
  - include: deploy_cluster.yml
  - include: setup_calamari.yml
