---
  - hosts: all
    sudo: yes
    roles:
      - common

  - hosts: ntp-server
    sudo: yes
    roles:
      - ntp-server

  - hosts: deploy
    sudo: yes
    roles:
      - deploy-server

  - hosts: ceph-node
    sudo: yes
    roles:
      - ceph-node
