---
  # initialize (setup config and install package)
  # need sudo privilege
  - hosts: all
    sudo: yes
    roles:
      - common

  - hosts: ntp-server
    sudo: yes
    roles:
      - ntp-server

  - hosts: deploy
    sudo: yes
    roles:
      - deploy-node-init

  - hosts: rados-node
    sudo: yes
    roles:
      - rados-node-init

  # Start deploying Ceph cluster
  - hosts: deploy
    roles:
      - deploy-node
