- name: Copy the script to node
  copy: src=roles/calamari-server/files/calamari_initial.expect dest=/tmp/.calamari_initial.expect

- name: Initialize calamari
  shell: expect /tmp/.calamari_initial.expect

- name: Enable supervisor and start
  service: name=supervisor enabled=yes state=started
